/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAQuote() {
        App classUnderTest = new App();
        assertNotNull("app should have a random quote", classUnderTest.getQuote());
    }
}
