/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Restaurant {
    String name;
    int rating;
    String priceCategory;

    public boolean someLibraryMethod() {
        return true;
    }

    public Restaurant(String name, int rating, String priceCategory){
        this.name = name;
        this.rating = rating;
        this.priceCategory = priceCategory;
    }

    public String toString() {
       return String.format("%s has a rating of %d of 5 and is a value of %s", this.name, this.rating, this.priceCategory);
    }
}
