/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        readJavaScriptFile("src/main/resources/gates.js");
    }

    public static String readJavaScriptFile(String filePath) {
        int lineNumber = 1;

        try {
            Scanner scanFile = new Scanner(new File(filePath));

            while(scanFile.hasNextLine()) {
                String line = scanFile.nextLine();

                if (!line.equals("") && !line.contains("if") && !line.contains("else") && !line.endsWith("{") && !line.endsWith("}") && !line.endsWith(";")) {
                    String outputString = String.format("Line %d: Missing semicolon", lineNumber);
                    System.out.println(outputString);
                }

                lineNumber++;

            }

        } catch(FileNotFoundException e) {
            System.out.println("File not found");
            System.out.println(e);
            return "";
        }
        return "No issues";
    }
}
