/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testRollMethod() {
        int array[] = Library.roll(5);
        assertEquals(5, array.length);
    }

    @Test public void testDuplicateFalseMethod() {
        int[] array = {1, 2, 3, 4, 5};
        boolean bool = Library.containsDuplicates(array);
        assertFalse(bool);
    }

    @Test public void testDuplicateTrueMethod() {
        int[] array = {1, 2, 2, 4, 5};
        boolean bool = Library.containsDuplicates(array);
        assertTrue(bool);
    }

    @Test public void testCalculateAverageMethod() {
        int[] array = {1, 1, 1, 1};
        float average = Library.calculateAverages(array);
        assertEquals(1.0f, average, 0.0f);
    }

    @Test public void testCalculateAverageTwoDMethod() {
        int[][] array = {{5, 1, 1, 1}, {2, 2, 2, 2}, {3, 3, 3, 3}};
        float average = Library.calculateTwoDAverages(array);
        assertEquals(2.0f, average, 0.0f);
    }
}
