/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class RestaurantTest {
    @Test public void testRestuarantString() {
        Restaurant restuarantObject = new Restaurant("Jimbos", 3, "$$");
        String expectedDescription = "Jimbos has a rating of 3 of 5 and is a value of $$";
        String actualDescription = restuarantObject.toString();
        assertEquals(expectedDescription, actualDescription);
    }

    @Test public void testReviewString() {
        Review reviewObject = new Review("Jimbos is good", "John", 3);
        String expectedDescription = "3 of 5 stars\nJimbos is good by John";
        String actualDescription = reviewObject.toString();
        assertEquals(expectedDescription, actualDescription);
    }
}
