/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.File;
import java.util.Random;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        System.out.println(new App().getQuote());
    }

    public String getQuote() {
        StringBuilder randomQuote = new StringBuilder();

        try {
            Scanner sc = new Scanner(new File("src/main/resources/recentquotes.json"));

            while (sc.hasNextLine()) {
                randomQuote.append(sc.nextLine());
            }

        } catch (Exception e) {
            System.out.println(e);
        }

        Gson gson = new Gson();
        Quote quoteData[] = gson.fromJson(randomQuote.toString(), Quote[].class);
        Random random = new Random();
        return quoteData[random.nextInt(quoteData.length)].text;
    }
}
