/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library {
    public static int[] roll(int num) {
        int[] array = new int[num];
        for (int i = 0; i < num; i ++){
            array[i] = (int) (Math.random() * 6);
        }

        return array;
    }

    public static boolean containsDuplicates(int[] array) {
        for (int i = 0; i < array.length; i ++) {
            for (int j = i + 1; j < array.length; j++) {
                if (array[i] == array[j]) {
                    return true;
                }
            }
        }

        return false;
    }

    public static float calculateAverages(int[] array) {
        int total = 0;

        for (int i = 0; i < array.length; i++) {
            total += array[i];
        }

        return (float) total / array.length;
    }

    public static float calculateTwoDAverages(int[][] array) {
        float[] averageArray = new float[array.length];

        for (int i = 0; i < array.length; i++) {
            averageArray[i] = calculateAverages(array[i]);
        }

        float lowest = averageArray[0];

        for (int i = 0; i < averageArray.length; i ++) {
            if (averageArray[i] < lowest) {
                lowest = averageArray[i];
            }
        }

        return lowest;
    }
}
